// This file is automatically generated. DO NOT EDIT.

package types

type StudentRecordExchangeData struct {
	StudentAcademicRecord struct {
		AcademicPerformanceSummary struct {
			GraduationDate int `xml:"GraduationDate"`
		} `xml:"AcademicPerformanceSummary"`
		CourseHistory struct {
			Term []struct {
				Courses struct {
					Course []struct {
						MarkingPeriods struct {
							MarkingPeriod struct {
								CourseCreditsAttempted float64 `xml:"CourseCreditsAttempted"`
								CourseCreditsEarned    float64 `xml:"CourseCreditsEarned"`
								DaysAbsent             int     `xml:"DaysAbsent"`
								GradeLevelWhenTaken    struct {
									Code          int `xml:"Code"`
									OtherCodeList struct {
										OtherCode struct {
											Codeset  string `xml:"Codeset,attr"`
											CharData string `xml:",chardata"`
										} `xml:"OtherCode"`
									} `xml:"OtherCodeList"`
								} `xml:"GradeLevelWhenTaken"`
								MarkData struct {
									Letter     string `xml:"Letter"`
									Narrative  string `xml:"Narrative"`
									Percentage int    `xml:"Percentage"`
								} `xml:"MarkData"`
							} `xml:"MarkingPeriod"`
						} `xml:"MarkingPeriods"`
						SIFExtendedElements struct {
							SIFExtendedElement []struct {
								Name     string `xml:"Name,attr"`
								CharData string `xml:",chardata"`
							} `xml:"SIF_ExtendedElement"`
						} `xml:"SIF_ExtendedElements"`
						SchoolCourseInfoData struct {
							CourseCode  string `xml:"CourseCode"`
							CourseTitle string `xml:"CourseTitle"`
						} `xml:"SchoolCourseInfoData"`
					} `xml:"Course"`
				} `xml:"Courses"`
				TermInfoData struct {
					SchoolYear int `xml:"SchoolYear"`
				} `xml:"TermInfoData"`
			} `xml:"Term"`
		} `xml:"CourseHistory"`
		ReportingDate               string `xml:"ReportingDate"`
		StudentSchoolEnrollmentData struct {
			GradeLevel struct {
				Code          int `xml:"Code"`
				OtherCodeList struct {
					OtherCode struct {
						Codeset  string `xml:"Codeset,attr"`
						CharData string `xml:",chardata"`
					} `xml:"OtherCode"`
				} `xml:"OtherCodeList"`
			} `xml:"GradeLevel"`
			SchoolAttended struct {
				LEAInfoData struct {
					LEAName         string `xml:"LEAName"`
					StateProvinceID string `xml:"StateProvinceId"`
				} `xml:"LEAInfoData"`
				SchoolInfoData struct {
					AddressList struct {
						Address struct {
							Type          int    `xml:"Type,attr"`
							City          string `xml:"City"`
							PostalCode    int    `xml:"PostalCode"`
							StateProvince string `xml:"StateProvince"`
							Street        struct {
								Line1 string `xml:"Line1"`
							} `xml:"Street"`
						} `xml:"Address"`
					} `xml:"AddressList"`
					LocalID           int `xml:"LocalId"`
					SchoolContactList struct {
						SchoolContact struct {
							ContactInfo struct {
								Name struct {
									Type      int    `xml:"Type,attr"`
									FirstName string `xml:"FirstName"`
									LastName  string `xml:"LastName"`
								} `xml:"Name"`
								PhoneNumberList struct {
									PhoneNumber struct {
										Type   int    `xml:"Type,attr"`
										Number string `xml:"Number"`
									} `xml:"PhoneNumber"`
								} `xml:"PhoneNumberList"`
								PositionTitle string `xml:"PositionTitle"`
							} `xml:"ContactInfo"`
						} `xml:"SchoolContact"`
					} `xml:"SchoolContactList"`
					SchoolName      string `xml:"SchoolName"`
					StateProvinceID int    `xml:"StateProvinceId"`
				} `xml:"SchoolInfoData"`
			} `xml:"SchoolAttended"`
		} `xml:"StudentSchoolEnrollmentData"`
	} `xml:"StudentAcademicRecord"`
	StudentDemographicRecord struct {
		ReportingDate       string `xml:"ReportingDate"`
		SIFExtendedElements struct {
			SIFExtendedElement []struct {
				Name           string `xml:"Name,attr"`
				PSCustomFields *struct {
					CustomFieldList struct {
						Entity      string `xml:"entity,attr"`
						CustomField []struct {
							IsCanonical string  `xml:"isCanonical,attr"`
							Name        string  `xml:"Name,attr"`
							Value       *string `xml:"Value,attr"`
						} `xml:"CustomField"`
					} `xml:"CustomFieldList"`
				} `xml:"PSCustomFields"`
				StudentDemographicRecordExtensions struct {
					EmailList struct {
						Email struct {
							Type     string `xml:"Type,attr"`
							CharData string `xml:",chardata"`
						} `xml:"Email"`
					} `xml:"EmailList"`
					EmergencyContacts struct {
						PSStudentContactType []struct {
							Name struct {
								Type      int     `xml:"Type,attr"`
								FirstName *string `xml:"FirstName"`
								LastName  string  `xml:"LastName"`
							} `xml:"Name"`
							PhoneNumberList *struct {
								PhoneNumber struct {
									Type   int    `xml:"Type,attr"`
									Number string `xml:"Number"`
								} `xml:"PhoneNumber"`
							} `xml:"PhoneNumberList"`
							Relationship struct {
								Code int `xml:"Code"`
							} `xml:"Relationship"`
						} `xml:"PS_StudentContactType"`
					} `xml:"EmergencyContacts"`
					Ethnicity          int    `xml:"Ethnicity"`
					ExcludeFromRanking string `xml:"ExcludeFromRanking"`
					FeeExemptionStatus int    `xml:"FeeExemptionStatus"`
					Health             struct {
						Allergies      string `xml:"Allergies"`
						Certifications struct {
							CertificationType struct{} `xml:"CertificationType"`
						} `xml:"Certifications"`
						Dentist struct {
							Fullname struct{} `xml:"Fullname"`
							Phone    struct {
								Type int `xml:"Type,attr"`
							} `xml:"Phone"`
						} `xml:"Dentist"`
						Doctor struct {
							Fullname string `xml:"Fullname"`
							Phone    struct {
								Type   int    `xml:"Type,attr"`
								Number string `xml:"Number"`
							} `xml:"Phone"`
						} `xml:"Doctor"`
						MedicalAlert struct {
							Message string `xml:"Message"`
						} `xml:"MedicalAlert"`
					} `xml:"Health"`
					HispanicLatino  string   `xml:"HispanicLatino"`
					Languages       struct{} `xml:"Languages"`
					RaceDecline     string   `xml:"RaceDecline"`
					StudentContacts struct {
						PSStudentContactType []struct {
							ContactFlags struct {
								ParentLegalGuardian string `xml:"ParentLegalGuardian"`
							} `xml:"ContactFlags"`
							Employer *string `xml:"Employer"`
							Name     struct {
								Type      int     `xml:"Type,attr"`
								FirstName *string `xml:"FirstName"`
								LastName  *string `xml:"LastName"`
							} `xml:"Name"`
							PhoneNumberList *struct {
								PhoneNumber struct {
									Type   int    `xml:"Type,attr"`
									Number string `xml:"Number"`
								} `xml:"PhoneNumber"`
							} `xml:"PhoneNumberList"`
							Relationship *struct {
								Code int `xml:"Code"`
							} `xml:"Relationship"`
						} `xml:"PS_StudentContactType"`
					} `xml:"StudentContacts"`
				} `xml:"StudentDemographicRecordExtensions"`
			} `xml:"SIF_ExtendedElement"`
		} `xml:"SIF_ExtendedElements"`
		StudentPersonalData struct {
			AddressList struct {
				Address []struct {
					Type          int    `xml:"Type,attr"`
					City          string `xml:"City"`
					PostalCode    int    `xml:"PostalCode"`
					StateProvince string `xml:"StateProvince"`
					Street        struct {
						Line1 string `xml:"Line1"`
					} `xml:"Street"`
				} `xml:"Address"`
			} `xml:"AddressList"`
			DemographicsData struct {
				BirthDate string `xml:"BirthDate"`
				Gender    string `xml:"Gender"`
				RaceList  struct {
					Race struct {
						Code string `xml:"Code"`
					} `xml:"Race"`
				} `xml:"RaceList"`
			} `xml:"DemographicsData"`
			LocalID int `xml:"LocalId"`
			Name    struct {
				Type       int    `xml:"Type,attr"`
				FirstName  string `xml:"FirstName"`
				LastName   string `xml:"LastName"`
				MiddleName string `xml:"MiddleName"`
			} `xml:"Name"`
			OtherIdList struct {
				OtherID struct {
					Type     int    `xml:"Type,attr"`
					CharData string `xml:",chardata"`
				} `xml:"OtherId"`
			} `xml:"OtherIdList"`
			PhoneNumberList struct {
				PhoneNumber struct {
					Type   int    `xml:"Type,attr"`
					Number string `xml:"Number"`
				} `xml:"PhoneNumber"`
			} `xml:"PhoneNumberList"`
			StateProvinceID int `xml:"StateProvinceId"`
		} `xml:"StudentPersonalData"`
	} `xml:"StudentDemographicRecord"`
	StudentRecordPackage struct {
		BinaryData struct {
			Description string `xml:"Description,attr"`
			MIMEType    string `xml:"MIMEType,attr"`
			CharData    string `xml:",chardata"`
		} `xml:"BinaryData"`
	} `xml:"StudentRecordPackage"`
}
